services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${USERNAME}
      RABBITMQ_DEFAULT_PASS: ${PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    volumes:
      - .containers/brokers/rabbitmq/data/:/var/lib/rabbitmq
      - .containers/brokers/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - .containers/cache/redis/data:/data
      - .containers/cache/redis/config/redis.conf:/usr/local/etc/redis/redis.conf

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${PASSWORD}
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - .containers/ddbb/mssqlserver/data:/var/opt/mssql/data
      - .containers/ddbb/mssqlserver/logs:/var/opt/mssql/log

  webapi:
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      sqlserver:
        condition: service_started
    environment:
      ASPNETCORE_HTTP_PORTS: 8000
      DATABASE: ${DATABASE}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    ports:
      - "8000:8000"
